// SPDX-License-Identifier: GPL-2.0
/*
 * Intel Elkhart Lake PCH pinctrl/GPIO driver
 *
 * Copyright (C) 2018, Intel Corporation
 * Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
 */

#include <linux/mod_devicetable.h>
#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/pm.h>
#include <linux/property.h>

#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-intel.h"

#define EHL_PAD_OWN	0x020
#define EHL_PADCFGLOCK	0x080
#define EHL_HOSTSW_OWN	0x0b0
#define EHL_GPI_IE	0x120

#define EHL_GPP(r, s, e)				\
	{						\
		.reg_num = (r),				\
		.base = (s),				\
		.size = ((e) - (s) + 1),		\
	}

#define EHL_COMMUNITY(b, s, e, g)			\
	{						\
		.barno = (b),				\
		.padown_offset = EHL_PAD_OWN,		\
		.padcfglock_offset = EHL_PADCFGLOCK,	\
		.hostown_offset = EHL_HOSTSW_OWN,	\
		.ie_offset = EHL_GPI_IE,		\
		.pin_base = (s),			\
		.npins = ((e) - (s) + 1),		\
		.gpps = (g),				\
		.ngpps = ARRAY_SIZE(g),			\
	}

/* Elkhart Lake */
static const struct pinctrl_pin_desc ehl_pins[] = {
	/* GPP_B */
	PINCTRL_PIN(0, "CORE_VID_0"),
	PINCTRL_PIN(1, "CORE_VID_1"),
	PINCTRL_PIN(2, "GPPC_B_2"),
	PINCTRL_PIN(3, "GPPC_B_3"),
	PINCTRL_PIN(4, "GPPC_B_4"),
	PINCTRL_PIN(5, "OSE_I2C0_SCLK"),
	PINCTRL_PIN(6, "OSE_I2C0_SDAT"),
	PINCTRL_PIN(7, "OSE_I2C1_SCLK"),
	PINCTRL_PIN(8, "OSE_I2C1_SDAT"),
	PINCTRL_PIN(9, "I2C5_SDA"),
	PINCTRL_PIN(10, "I2C5_SCL"),
	PINCTRL_PIN(11, "PMCALERTB"),
	PINCTRL_PIN(12, "SLP_S0B"),
	PINCTRL_PIN(13, "PLTRSTB"),
	PINCTRL_PIN(14, "SPKR"),
	PINCTRL_PIN(15, "GSPI0_CS0B"),
	PINCTRL_PIN(16, "GSPI0_CLK"),
	PINCTRL_PIN(17, "GSPI0_MISO"),
	PINCTRL_PIN(18, "GSPI0_MOSI"),
	PINCTRL_PIN(19, "GSPI1_CS0B"),
	PINCTRL_PIN(20, "GSPI1_CLK"),
	PINCTRL_PIN(21, "GSPI1_MISO"),
	PINCTRL_PIN(22, "GSPI1_MOSI"),
	PINCTRL_PIN(23, "GPPC_B_23"),
	PINCTRL_PIN(24, "GSPI0_CLK_LOOPBK"),
	PINCTRL_PIN(25, "GSPI1_CLK_LOOPBK"),
	/* GPP_T */
	PINCTRL_PIN(26, "OSE_QEPA_2"),
	PINCTRL_PIN(27, "OSE_QEPB_2"),
	PINCTRL_PIN(28, "OSE_QEPI_2"),
	PINCTRL_PIN(29, "OSE_PWM10"),
	PINCTRL_PIN(30, "RGMII0_INT"),
	PINCTRL_PIN(31, "RGMII0_RESET"),
	PINCTRL_PIN(32, "RGMII0_AUXTS"),
	PINCTRL_PIN(33, "RGMII0_PPS"),
	PINCTRL_PIN(34, "OSE_UART2_RXD"),
	PINCTRL_PIN(35, "OSE_UART2_TXD"),
	PINCTRL_PIN(36, "OSE_UART2_RTSB"),
	PINCTRL_PIN(37, "OSE_UART2_CTSB"),
	PINCTRL_PIN(38, "OSE_HSUART2_DE"),
	PINCTRL_PIN(39, "OSE_HSUART2_RE"),
	PINCTRL_PIN(40, "OSE_HSUART2_EN"),
	PINCTRL_PIN(41, "OSE_PWM11"),
	/* GPP_A */
	PINCTRL_PIN(42, "ESPI_IO_0"),
	PINCTRL_PIN(43, "ESPI_IO_1"),
	PINCTRL_PIN(44, "ESPI_IO_2"),
	PINCTRL_PIN(45, "ESPI_IO_3"),
	PINCTRL_PIN(46, "ESPI_CSB"),
	PINCTRL_PIN(47, "ESPI_CLK"),
	PINCTRL_PIN(48, "ESPI_RESETB"),
	PINCTRL_PIN(49, "I2S2_SCLK"),
	PINCTRL_PIN(50, "I2S2_SFRM"),
	PINCTRL_PIN(51, "I2S2_TXD"),
	PINCTRL_PIN(52, "I2S2_RXD"),
	PINCTRL_PIN(53, "I2S3_SCLK"),
	PINCTRL_PIN(54, "I2S3_SFRM"),
	PINCTRL_PIN(55, "I2S3_TXD"),
	PINCTRL_PIN(56, "I2S3_RXD"),
	PINCTRL_PIN(57, "USB2_OCB_2"),
	PINCTRL_PIN(58, "USB2_OCB_3"),
	PINCTRL_PIN(59, "USB2_OCB_1"),
	PINCTRL_PIN(60, "GPPC_A_18"),
	PINCTRL_PIN(61, "I2S5_SCLK"),
	PINCTRL_PIN(62, "I2S5_SFRM"),
	PINCTRL_PIN(63, "I2S5_TXD"),
	PINCTRL_PIN(64, "I2S5_RXD"),
	PINCTRL_PIN(65, "I2S1_SCLK"),
	PINCTRL_PIN(66, "ESPI_CLK_LOOPBK"),
	/* GPP_G */
	PINCTRL_PIN(67, "SD3_CMD"),
	PINCTRL_PIN(68, "SD3_D0"),
	PINCTRL_PIN(69, "SD3_D1"),
	PINCTRL_PIN(70, "SD3_D2"),
	PINCTRL_PIN(71, "SD3_D3"),
	PINCTRL_PIN(72, "SD3_CDB"),
	PINCTRL_PIN(73, "SD3_CLK"),
	PINCTRL_PIN(74, "SD3_WP"),
	/* GPP_H */
	PINCTRL_PIN(75, "GPPC_H_0"),
	PINCTRL_PIN(76, "GPPC_H_1"),
	PINCTRL_PIN(77, "GPPC_H_2"),
	PINCTRL_PIN(78, "GPPC_H_3"),
	PINCTRL_PIN(79, "I2C2_SDA"),
	PINCTRL_PIN(80, "I2C2_SCL"),
	PINCTRL_PIN(81, "I2C3_SDA"),
	PINCTRL_PIN(82, "I2C3_SCL"),
	PINCTRL_PIN(83, "I2C4_SDA"),
	PINCTRL_PIN(84, "I2C4_SCL"),
	PINCTRL_PIN(85, "SRCCLKREQB_4"),
	PINCTRL_PIN(86, "OSE_PWM6"),
	PINCTRL_PIN(87, "OSE_UART1_RXD"),
	PINCTRL_PIN(88, "OSE_UART1_TXD"),
	PINCTRL_PIN(89, "OSE_UART1_RTSB"),
	PINCTRL_PIN(90, "OSE_UART1_CTSB"),
	PINCTRL_PIN(91, "OSE_PWM7"),
	PINCTRL_PIN(92, "GPPC_H_17"),
	PINCTRL_PIN(93, "CPU_C10_GATEB"),
	PINCTRL_PIN(94, "OSE_PWM8"),
	PINCTRL_PIN(95, "OSE_PWM9"),
	PINCTRL_PIN(96, "OSE_HSUART1_DE"),
	PINCTRL_PIN(97, "OSE_HSUART1_RE"),
	PINCTRL_PIN(98, "OSE_HSUART1_EN"),
	/* GPP_D */
	PINCTRL_PIN(99, "OSE_QEPA_0"),
	PINCTRL_PIN(100, "OSE_QEPB_0"),
	PINCTRL_PIN(101, "OSE_QEPI_0"),
	PINCTRL_PIN(102, "OSE_PWM1"),
	PINCTRL_PIN(103, "OSE_PWM2"),
	PINCTRL_PIN(104, "SRCCLKREQB_0"),
	PINCTRL_PIN(105, "SRCCLKREQB_1"),
	PINCTRL_PIN(106, "SRCCLKREQB_2"),
	PINCTRL_PIN(107, "SRCCLKREQB_3"),
	PINCTRL_PIN(108, "OSE_SPI0_CSB"),
	PINCTRL_PIN(109, "OSE_SPI0_SCLK"),
	PINCTRL_PIN(110, "OSE_SPI0_MISO"),
	PINCTRL_PIN(111, "OSE_SPI0_MOSI"),
	PINCTRL_PIN(112, "OSE_QEPA_1"),
	PINCTRL_PIN(113, "OSE_QEPB_1"),
	PINCTRL_PIN(114, "OSE_PWM3"),
	PINCTRL_PIN(115, "OSE_QEPI_1"),
	PINCTRL_PIN(116, "OSE_PWM4"),
	PINCTRL_PIN(117, "OSE_PWM5"),
	PINCTRL_PIN(118, "I2S_MCLK1_OUT"),
	PINCTRL_PIN(119, "GSPI2_CLK_LOOPBK"),
	/* GPP_U */
	PINCTRL_PIN(120, "OSE_QEPA_3"),
	PINCTRL_PIN(121, "OSE_QEPB_3"),
	PINCTRL_PIN(122, "OSE_QEPI_3"),
	PINCTRL_PIN(123, "OSE_PWM12"),
	PINCTRL_PIN(124, "ISI_SPIM_CS"),
	PINCTRL_PIN(125, "ISI_SPIM_SCLK"),
	PINCTRL_PIN(126, "ISI_SPIM_DATA"),
	PINCTRL_PIN(127, "OSE_PWM13"),
	PINCTRL_PIN(128, "ISI_SPIS_CS"),
	PINCTRL_PIN(129, "ISI_SPIS_SCLK"),
	PINCTRL_PIN(130, "ISI_SPIS_DATA"),
	PINCTRL_PIN(131, "OSE_PWM14"),
	PINCTRL_PIN(132, "ISI_CHX_OKNOK_0"),
	PINCTRL_PIN(133, "ISI_CHX_OKNOK_1"),
	PINCTRL_PIN(134, "ISI_CHX_RLY_SWTCH"),
	PINCTRL_PIN(135, "ISI_CHX_PMIC_EN"),
	PINCTRL_PIN(136, "ISI_OKNOK_0"),
	PINCTRL_PIN(137, "ISI_OKNOK_1"),
	PINCTRL_PIN(138, "ISI_ALERT#"),
	PINCTRL_PIN(139, "OSE_PWM15"),
	PINCTRL_PIN(140, "GSPI3_CLK_LOOPBK"),
	PINCTRL_PIN(141, "GSPI4_CLK_LOOPBK"),
	PINCTRL_PIN(142, "GSPI5_CLK_LOOPBK"),
	PINCTRL_PIN(143, "GSPI6_CLK_LOOPBK"),
	/* vGPIO */
	PINCTRL_PIN(144, "CNV_BTEN"),
	PINCTRL_PIN(145, "CNV_BT_HOST_WAKEB"),
	PINCTRL_PIN(146, "CNV_BT_IF_SELECT"),
	PINCTRL_PIN(147, "vCNV_BT_UART_TXD"),
	PINCTRL_PIN(148, "vCNV_BT_UART_RXD"),
	PINCTRL_PIN(149, "vCNV_BT_UART_CTS_B"),
	PINCTRL_PIN(150, "vCNV_BT_UART_RTS_B"),
	PINCTRL_PIN(151, "vCNV_MFUART1_TXD"),
	PINCTRL_PIN(152, "vCNV_MFUART1_RXD"),
	PINCTRL_PIN(153, "vCNV_MFUART1_CTS_B"),
	PINCTRL_PIN(154, "vCNV_MFUART1_RTS_B"),
	PINCTRL_PIN(155, "vUART0_TXD"),
	PINCTRL_PIN(156, "vUART0_RXD"),
	PINCTRL_PIN(157, "vUART0_CTS_B"),
	PINCTRL_PIN(158, "vUART0_RTS_B"),
	PINCTRL_PIN(159, "vISH_UART0_TXD"),
	PINCTRL_PIN(160, "vISH_UART0_RXD"),
	PINCTRL_PIN(161, "vISH_UART0_CTS_B"),
	PINCTRL_PIN(162, "vISH_UART0_RTS_B"),
	PINCTRL_PIN(163, "vCNV_BT_I2S_BCLK"),
	PINCTRL_PIN(164, "vCNV_BT_I2S_WS_SYNC"),
	PINCTRL_PIN(165, "vCNV_BT_I2S_SDO"),
	PINCTRL_PIN(166, "vCNV_BT_I2S_SDI"),
	PINCTRL_PIN(167, "vI2S2_SCLK"),
	PINCTRL_PIN(168, "vI2S2_SFRM"),
	PINCTRL_PIN(169, "vI2S2_TXD"),
	PINCTRL_PIN(170, "vI2S2_RXD"),
	/* vGPIO_3 */
	PINCTRL_PIN(171, "P0_CLKREQTX_VW_0"),
	PINCTRL_PIN(172, "P0_CLKREQTX_VW_1"),
	PINCTRL_PIN(173, "P0_CLKREQTX_VW_2"),
	PINCTRL_PIN(174, "P0_CLKREQTX_VW_3"),
	PINCTRL_PIN(175, "P0_CLKREQTX_VW_4"),
	PINCTRL_PIN(176, "P0_CLKREQTX_VW_5"),
	PINCTRL_PIN(177, "P0_CLKREQTX_VW_6"),
	PINCTRL_PIN(178, "P0_CLKREQTX_VW_7"),
	PINCTRL_PIN(179, "P0_CLKREQTX_VW_8"),
	PINCTRL_PIN(180, "P0_CLKREQTX_VW_9"),
	PINCTRL_PIN(181, "P0_CLKREQTX_VW_10"),
	PINCTRL_PIN(182, "P0_CLKREQTX_VW_11"),
	PINCTRL_PIN(183, "P0_CLKREQTX_VW_12"),
	PINCTRL_PIN(184, "P0_CLKREQTX_VW_13"),
	PINCTRL_PIN(185, "P0_CLKREQTX_VW_14"),
	PINCTRL_PIN(186, "P0_CLKREQTX_VW_15"),
	PINCTRL_PIN(187, "P1_CLKREQTX_VW_0"),
	PINCTRL_PIN(188, "P1_CLKREQTX_VW_1"),
	PINCTRL_PIN(189, "P1_CLKREQTX_VW_2"),
	PINCTRL_PIN(190, "P1_CLKREQTX_VW_3"),
	PINCTRL_PIN(191, "P1_CLKREQTX_VW_4"),
	PINCTRL_PIN(192, "P1_CLKREQTX_VW_5"),
	PINCTRL_PIN(193, "P1_CLKREQTX_VW_6"),
	PINCTRL_PIN(194, "P1_CLKREQTX_VW_7"),
	PINCTRL_PIN(195, "P1_CLKREQTX_VW_8"),
	PINCTRL_PIN(196, "P1_CLKREQTX_VW_9"),
	PINCTRL_PIN(197, "P1_CLKREQTX_VW_10"),
	PINCTRL_PIN(198, "P1_CLKREQTX_VW_11"),
	PINCTRL_PIN(199, "P1_CLKREQTX_VW_12"),
	PINCTRL_PIN(200, "P1_CLKREQTX_VW_13"),
	PINCTRL_PIN(201, "P1_CLKREQTX_VW_14"),
	PINCTRL_PIN(202, "P1_CLKREQTX_VW_15"),
	PINCTRL_PIN(203, "P2_CLKREQTX_VW_0"),
	PINCTRL_PIN(204, "P2_CLKREQTX_VW_1"),
	PINCTRL_PIN(205, "P2_CLKREQTX_VW_2"),
	PINCTRL_PIN(206, "P2_CLKREQTX_VW_3"),
	PINCTRL_PIN(207, "P2_CLKREQTX_VW_4"),
	PINCTRL_PIN(208, "P2_CLKREQTX_VW_5"),
	PINCTRL_PIN(209, "P2_CLKREQTX_VW_6"),
	PINCTRL_PIN(210, "P2_CLKREQTX_VW_7"),
	PINCTRL_PIN(211, "P2_CLKREQTX_VW_8"),
	PINCTRL_PIN(212, "P2_CLKREQTX_VW_9"),
	PINCTRL_PIN(213, "P2_CLKREQTX_VW_10"),
	PINCTRL_PIN(214, "P2_CLKREQTX_VW_11"),
	PINCTRL_PIN(215, "P2_CLKREQTX_VW_12"),
	PINCTRL_PIN(216, "P2_CLKREQTX_VW_13"),
	PINCTRL_PIN(217, "P2_CLKREQTX_VW_14"),
	PINCTRL_PIN(218, "P2_CLKREQTX_VW_15"),
	PINCTRL_PIN(219, "P3_CLKREQTX_VW_0"),
	PINCTRL_PIN(220, "P3_CLKREQTX_VW_1"),
	PINCTRL_PIN(221, "P3_CLKREQTX_VW_2"),
	PINCTRL_PIN(222, "P3_CLKREQTX_VW_3"),
	PINCTRL_PIN(223, "P3_CLKREQTX_VW_4"),
	PINCTRL_PIN(224, "P3_CLKREQTX_VW_5"),
	PINCTRL_PIN(225, "P3_CLKREQTX_VW_6"),
	PINCTRL_PIN(226, "P3_CLKREQTX_VW_7"),
	PINCTRL_PIN(227, "P3_CLKREQTX_VW_8"),
	PINCTRL_PIN(228, "P3_CLKREQTX_VW_9"),
	PINCTRL_PIN(229, "P3_CLKREQTX_VW_10"),
	PINCTRL_PIN(230, "P3_CLKREQTX_VW_11"),
	PINCTRL_PIN(231, "P3_CLKREQTX_VW_12"),
	PINCTRL_PIN(232, "P3_CLKREQTX_VW_13"),
	PINCTRL_PIN(233, "P3_CLKREQTX_VW_14"),
	PINCTRL_PIN(234, "P3_CLKREQTX_VW_15"),
	PINCTRL_PIN(235, "P0_CLKREQRX_VW_0"),
	PINCTRL_PIN(236, "P0_CLKREQRX_VW_1"),
	PINCTRL_PIN(237, "P0_CLKREQRX_VW_2"),
	PINCTRL_PIN(238, "P0_CLKREQRX_VW_3"),
	PINCTRL_PIN(239, "P1_CLKREQRX_VW_0"),
	PINCTRL_PIN(240, "P1_CLKREQRX_VW_1"),
	PINCTRL_PIN(241, "P1_CLKREQRX_VW_2"),
	PINCTRL_PIN(242, "P1_CLKREQRX_VW_3"),
	PINCTRL_PIN(243, "P2_CLKREQRX_VW_0"),
	PINCTRL_PIN(244, "P2_CLKREQRX_VW_1"),
	PINCTRL_PIN(245, "P2_CLKREQRX_VW_2"),
	PINCTRL_PIN(246, "P2_CLKREQRX_VW_3"),
	PINCTRL_PIN(247, "P3_CLKREQRX_VW_0"),
	PINCTRL_PIN(248, "P3_CLKREQRX_VW_1"),
	PINCTRL_PIN(249, "P3_CLKREQRX_VW_2"),
	PINCTRL_PIN(250, "P3_CLKREQRX_VW_3"),
	PINCTRL_PIN(251, "ESPI_USB_OCB_0"),
	PINCTRL_PIN(252, "ESPI_USB_OCB_1"),
	PINCTRL_PIN(253, "ESPI_USB_OCB_2"),
	PINCTRL_PIN(254, "ESPI_USB_OCB_3"),
	PINCTRL_PIN(255, "USB_CPU_OCB_0"),
	PINCTRL_PIN(256, "USB_CPU_OCB_1"),
	PINCTRL_PIN(257, "USB_CPU_OCB_2"),
	PINCTRL_PIN(258, "USB_CPU_OCB_3"),
	PINCTRL_PIN(259, "PEG_LNK_DN_0"),
	PINCTRL_PIN(260, "PEG_LNK_DN_1"),
	PINCTRL_PIN(261, "PEG_LNK_DN_2"),
	PINCTRL_PIN(262, "PEG_LNK_DN_3"),
	/* GPP_C */
	PINCTRL_PIN(263, "SMBCLK"),
	PINCTRL_PIN(264, "SMBDATA"),
	PINCTRL_PIN(265, "OSE_PWM0"),
	PINCTRL_PIN(266, "RGMII0_MDC"),
	PINCTRL_PIN(267, "RGMII0_MDIO"),
	PINCTRL_PIN(268, "GPPC_C_5"),
	PINCTRL_PIN(269, "RGMII1_MDC"),
	PINCTRL_PIN(270, "RGMII1_MDIO"),
	PINCTRL_PIN(271, "GPPC_C_8"),
	PINCTRL_PIN(272, "OSE_HSUART0_EN"),
	PINCTRL_PIN(273, "OSE_HSUART0_DE"),
	PINCTRL_PIN(274, "OSE_HSUART0_RE"),
	PINCTRL_PIN(275, "OSE_UART0_RXD"),
	PINCTRL_PIN(276, "OSE_UART0_TXD"),
	PINCTRL_PIN(277, "OSE_UART0_RTSB"),
	PINCTRL_PIN(278, "OSE_UART0_CTSB"),
	PINCTRL_PIN(279, "RGMII2_MDC"),
	PINCTRL_PIN(280, "RGMII2_MDIO"),
	PINCTRL_PIN(281, "GPPC_C_18"),
	PINCTRL_PIN(282, "GPPC_C_19"),
	PINCTRL_PIN(283, "OSE_UART4_RXD"),
	PINCTRL_PIN(284, "OSE_UART4_TXD"),
	PINCTRL_PIN(285, "OSE_UART4_RTSB"),
	PINCTRL_PIN(286, "OSE_UART4_CTSB"),
	/* GPP_F */
	PINCTRL_PIN(287, "CNV_BRI_DT"),
	PINCTRL_PIN(288, "CNV_BRI_RSP"),
	PINCTRL_PIN(289, "CNV_RGI_DT"),
	PINCTRL_PIN(290, "CNV_RGI_RSP"),
	PINCTRL_PIN(291, "CNV_RF_RESET_B"),
	PINCTRL_PIN(292, "GPPC_F_5"),
	PINCTRL_PIN(293, "CNV_PA_BLANKING"),
	PINCTRL_PIN(294, "OSE_I2S1_SCLK"),
	PINCTRL_PIN(295, "I2S_MCLK2_INOUT"),
	PINCTRL_PIN(296, "BOOTMPC"),
	PINCTRL_PIN(297, "OSE_I2S1_SFRM"),
	PINCTRL_PIN(298, "DDSP_HPD_C"),
	PINCTRL_PIN(299, "GSXDOUT"),
	PINCTRL_PIN(300, "GSXSLOAD"),
	PINCTRL_PIN(301, "GSXDIN"),
	PINCTRL_PIN(302, "GSXSRESETB"),
	PINCTRL_PIN(303, "GSXCLK"),
	PINCTRL_PIN(304, "GPPC_F_17"),
	PINCTRL_PIN(305, "OSE_I2S1_TXD"),
	PINCTRL_PIN(306, "OSE_I2S1_RXD"),
	PINCTRL_PIN(307, "EXT_PWR_GATEB"),
	PINCTRL_PIN(308, "EXT_PWR_GATE2B"),
	PINCTRL_PIN(309, "VNN_CTRL"),
	PINCTRL_PIN(310, "V1P05_CTRL"),
	PINCTRL_PIN(311, "GPPF_CLK_LOOPBACK"),
	/* GPP_E */
	PINCTRL_PIN(312, "DDPB_CTRLDATA"),
	PINCTRL_PIN(313, "GPPC_E_1"),
	PINCTRL_PIN(314, "GPPC_E_2"),
	PINCTRL_PIN(315, "DDSP_HPD_B"),
	PINCTRL_PIN(316, "SATA_DEVSLP_0"),
	PINCTRL_PIN(317, "SATA_DEVSLP_1"),
	PINCTRL_PIN(318, "GPPC_E_6"),
	PINCTRL_PIN(319, "DDPB_CTRLCLK"),
	PINCTRL_PIN(320, "GPPC_E_8"),
	PINCTRL_PIN(321, "USB2_OCB_0"),
	PINCTRL_PIN(322, "GPPC_E_10"),
	PINCTRL_PIN(323, "GPPC_E_11"),
	PINCTRL_PIN(324, "GPPC_E_12"),
	PINCTRL_PIN(325, "GPPC_E_13"),
	PINCTRL_PIN(326, "DDSP_HPD_A"),
	PINCTRL_PIN(327, "OSE_I2S0_TXD"),
	PINCTRL_PIN(328, "OSE_I2S0_RXD"),
	PINCTRL_PIN(329, "GPPC_E_17"),
	PINCTRL_PIN(330, "DDPA_CTRLDATA"),
	PINCTRL_PIN(331, "DDPA_CTRLCLK"),
	PINCTRL_PIN(332, "OSE_I2S0_SCLK"),
	PINCTRL_PIN(333, "OSE_I2S0_SFRM"),
	PINCTRL_PIN(334, "DDPC_CTRLDATA"),
	PINCTRL_PIN(335, "DDPC_CTRLCLK"),
	PINCTRL_PIN(336, "SPI1_CLK_LOOPBK"),
	/* GPP_R */
	PINCTRL_PIN(337, "HDA_BCLK"),
	PINCTRL_PIN(338, "HDA_SYNC"),
	PINCTRL_PIN(339, "HDA_SDO"),
	PINCTRL_PIN(340, "HDA_SDI_0"),
	PINCTRL_PIN(341, "HDA_RSTB"),
	PINCTRL_PIN(342, "HDA_SDI_1"),
	PINCTRL_PIN(343, "GPP_R_6"),
	PINCTRL_PIN(344, "GPP_R_7"),
};

static const struct intel_padgroup ehl_community0_gpps[] = {
	EHL_GPP(0, 0, 25),	/* GPP_B */
	EHL_GPP(1, 26, 41),	/* GPP_T */
	EHL_GPP(2, 42, 66),	/* GPP_A */
	EHL_GPP(3, 67, 74),	/* GPP_G */
};

static const struct intel_padgroup ehl_community1_gpps[] = {
	EHL_GPP(0, 75, 98),	/* GPP_H */
	EHL_GPP(1, 99, 119),	/* GPP_D */
	EHL_GPP(2, 120, 143),	/* GPP_U */
	EHL_GPP(3, 144, 170),	/* vGPIO */
};

static const struct intel_padgroup ehl_community3_gpps[] = {
	EHL_GPP(0, 171, 202),	/* vGPIO_3_0 */
	EHL_GPP(1, 203, 234),	/* vGPIO_3_1 */
	EHL_GPP(2, 235, 262),	/* vGPIO_3_2 */
};

static const struct intel_padgroup ehl_community4_gpps[] = {
	EHL_GPP(0, 263, 286),	/* GPP_C */
	EHL_GPP(1, 287, 311),	/* GPP_F */
	EHL_GPP(2, 312, 336),	/* GPP_E */
};

static const struct intel_padgroup ehl_community5_gpps[] = {
	EHL_GPP(0, 337, 344),	/* GPP_R */
};

static const struct intel_community ehl_communities[] = {
	EHL_COMMUNITY(0, 0, 74, ehl_community0_gpps),
	EHL_COMMUNITY(1, 75, 170, ehl_community1_gpps),
	EHL_COMMUNITY(2, 171, 262, ehl_community3_gpps),
	EHL_COMMUNITY(3, 263, 336, ehl_community4_gpps),
	EHL_COMMUNITY(4, 337, 344, ehl_community5_gpps),
};

static const struct intel_pingroup ehl_groups[] = {
};

static const struct intel_function ehl_functions[] = {
};

static const struct intel_pinctrl_soc_data ehl_soc_data = {
	.pins = ehl_pins,
	.npins = ARRAY_SIZE(ehl_pins),
	.groups = ehl_groups,
	.ngroups = ARRAY_SIZE(ehl_groups),
	.functions = ehl_functions,
	.nfunctions = ARRAY_SIZE(ehl_functions),
	.communities = ehl_communities,
	.ncommunities = ARRAY_SIZE(ehl_communities),
};

static const struct acpi_device_id ehl_pinctrl_acpi_match[] = {
	{ "INTC1020", (kernel_ulong_t)&ehl_soc_data },
	{}
};
MODULE_DEVICE_TABLE(acpi, ehl_pinctrl_acpi_match);

static int ehl_pinctrl_probe(struct platform_device *pdev)
{
	const struct intel_pinctrl_soc_data *soc_data;

	soc_data = device_get_match_data(&pdev->dev);
	return intel_pinctrl_probe(pdev, soc_data);
}

static const struct dev_pm_ops ehl_pinctrl_pm_ops = {
	SET_LATE_SYSTEM_SLEEP_PM_OPS(intel_pinctrl_suspend, intel_pinctrl_resume)
};

static struct platform_driver ehl_pinctrl_driver = {
	.probe = ehl_pinctrl_probe,
	.driver = {
		.name = "elkhartlake-pinctrl",
		.acpi_match_table = ehl_pinctrl_acpi_match,
		.pm = &ehl_pinctrl_pm_ops,
	},
};

module_platform_driver(ehl_pinctrl_driver);

MODULE_AUTHOR("Andy Shevchenko <andriy.shevchenko@linux.intel.com>");
MODULE_DESCRIPTION("Intel Elkhart Lake PCH pinctrl/GPIO driver");
MODULE_LICENSE("GPL v2");
